name: validate-and-deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      # 1) Clean + de-dupe → dist/genz-dictionary.json
      - name: Fix dictionary
        run: npm run fix:dict

      # 2) Show a quick preview in logs
      - name: Preview head
        run: |
          head -n 40 dist/genz-dictionary.json || true
          echo "Files in dist:" && ls -la dist

      # 3) Validate the cleaned file
      - name: Validate dictionary
        run: npm run validate:dict

      # 4) Prepare & upload Pages artifact (serve dist/ as site root)
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
